#! /bin/bash
#
# postrm script for #PACKAGE#
#

set -e

# reanable 10_linux on btrfs / file systems

if [ ! -x /etc/grub.d/10_linux ]; then
    chmod 755 /etc/grub.d/10_linux
fi


# remove systemd mask links on none btrfs / file systems

if [ -h /etc/systemd/system/siduction_btrfs.path ]; then
    exec $(systemctl unmask siduction_btrfs.path > /dev/null 2>&1)
fi
if [ -h /etc/systemd/system/siduction_btrfs.timer ]; then
    exec $(systemctl unmask siduction_btrfs.timer > /dev/null 2>&1)
fi


#DEBHELPER#

exit 0
