#!/usr/bin/bash
#
# preinst script for #PACKAGE#
#

set -e

# Now we use the snapper plugin dir.
if [ ! -d /usr/lib/snapper/plugins/ ]; then
	mkdir /usr/lib/snapper/plugins
fi

if btrfs_default=$(btrfs subvolume get-default / 2>/dev/null); then
	# Query the btrfs default subvolume and the booted subvolume.
	# Declare required variables.
	#
	# Subvolume, that is set to default in Btrfs
	if grep -q "@snapshots/" <<< ${btrfs_default}; then
		btrfs_default=$(sed -E 's|[^@]*@|@|' <<< ${btrfs_default})
		default_nr=$(cut -d '/' -f 2 <<< ${btrfs_default})
		key=$((10000 - "$default_nr")) # $key is only required in systemd-boot.
	
	else
		if ! grep @ <<< ${btrfs_default} &>/dev/null; then
			exec $(btrfs subvolume set-default 256 / )
		fi
		btrfs_default="@"
		default_nr="@"
		key="10000" # $key is only required in systemd-boot.
	fi
	
	# Create PRETTY_NAME extension.
	token_ext="-snapshot-$default_nr"
	name_ext=", snapshot $default_nr"
else
	token_ext=""
	name_ext=""
fi


# The default installation uses GRUB.
# The files 'os-release' and 'entry-token' are used by systemd-boot.
# We create them to be compatible with systemd.
echo "TUXEDO OS"  > /etc/kernel/entry-token

#DEBHELPER#

exit 0

