#! /bin/bash
#
# postinst script for #PACKAGE#
#

set -e

if [ ! $( systemctl status siduction_btrfs.path | awk '/masked/{print $2}' 2>/dev/null) ]; then
    systemctl enable siduction_btrfs.timer siduction_btrfs.path
fi

#DEBHELPER#

exit 0
