#!/usr/bin/bash
#
# preinst script for #PACKAGE#
#

set -e

. /etc/default/distro

if [ -h /etc/os-release ]; then
	rm /etc/os-release
fi

name_firstup=$(echo $FLL_DISTRO_CODENAME_SAFE | sed -e 's/\(.\)/\u\1/')
flav_upper=$(echo $FLL_FLAVOUR | tr '[:lower:]' '[:upper:]')

cat << EOF >> /etc/os-release
PRETTY_NAME="$FLL_DISTRO_NAME $name_firstup $flav_upper"
NAME="$FLL_DISTRO_NAME"
VERSION_CODENAME=$FLL_DISTRO_CODENAME_SAFE
VERSION="$name_firstup"
VARIANT="$flav_upper"
VARIANT_ID=$FLL_FLAVOUR
ID=$FLL_DISTRO_NAME
ID_LIKE=debian
HOME_URL="https://siduction.org"
SUPPORT_URL="https://forum.siduction.org"
EOF


#DEBHELPER#

exit 0
