#! /bin/bash
#
# postinst script for #PACKAGE#
#

set -e

ROOTFSTYP=$( grep '[[:space:]]\+/[[:space:]]\+' /etc/fstab | awk '{ print $3 }' )

if [ "x$ROOTFSTYP" = "xbtrfs" ]; then
    systemctl enable --now siduction_btrfs.timer siduction_btrfs.path
fi

#DEBHELPER#

exit 0
