#! /bin/bash
#
# postinst script for siduction-btrfs
#

set -e

ROOTFSTYP=$( grep '[[:space:]]\+/[[:space:]]\+' /etc/fstab | awk '{ print $3 }' )

if [ "x$ROOTFSTYP" = "xbtrfs" ]; then
    systemctl enable --now siduction_btrfs.timer siduction_btrfs.path
fi



exit 0
